chore: update homepage in gemspec to shakacode organization
shakacode/package_json pull request #6
Opened 2023-09-28 21:04 UTC by ahangarha

Update the organization in the GitHub URL in the gemspec file to `shakacode`.

2023-09-28 21:05 UTC, G-Rath requested changes
We might as well update the email at the same time

2023-09-28 21:15 UTC, ahangarha commented
@justin808 May you share the information to include in the gemspec?

2023-11-01 22:30 UTC, justin808 commented
@G-Rath please merge if this is ready.

2023-11-01 22:33 UTC, G-Rath approved these changes

2023-11-01 22:33 UTC, merged